### PR TITLE
change error format

### PR DESCRIPTION
**Pull request by ayrat555**
fixes https://github.com/omgnetwork/ex_plasma/issues/57
I grepped elixir-omg. it seems it doesn't use the old name

### CODE REVIEW

**Comment by InoMurko** [comment]
ugh good catch. why didn't dialyzer catch this?

**Comment by ayrat555** [comment]
@InoMurko it wasn't the wrong type definition issue. This PR changes naming for `exceeds_maximum_value` => `cannot_exceed_maximum_value`

**Comment by InoMurko** [comment]
Now I'm curious. Where did you notice `cannot_exceed_maximum_value`? I can't find it

**Comment by ayrat555** [comment]
@InoMurko Arthur suggested in the description of the issue
```
Currently, we use a few errors that follow the pattern of cannot_something_something. We should change errors like exceeds_maximum_value to cannot_exceed_maximum_value or something
```
https://github.com/omgnetwork/ex_plasma/issues/57

**Comment by ayrat555** [comment]
@mederic-p ping

**Pull request merged**
